# Site settings
title: hannenz
email: johannes.braun@hannenz.de
description: > # this means to ignore newlines until "baseurl:"
  a blog. mine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hannenz.de" # the base hostname & protocol for your site
twitter_username: jbhannenz
github_username:  hannenz

# Build settings
markdown: kramdown
reading_time:
  second_plural: "s"
  minute_singular: "min"
  minute_plural: "min"
